src/Entity/GrindReport.php
<?php
declare(strict_types=1);

namespace App\Entity;

use App\RelativeMeasuringPoint;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Uid\Uuid;

/**
 * @ORM\Entity()
 */
class GrindReport
{
    static $typeMap = [
        0 => 'Manual',
        1 => 'Purge',
        2 => 'Grind by time',
        3 => 'Grind by weight',
    ];

    /**
     * @ORM\Column(type="uuid", nullable=false)
     * @ORM\Id()
     */
    private $id;

    /**
     * @var \DateTimeImmutable
     * @ORM\Column(type="datetimetz_immutable", nullable=false)
     */
    private $createdAt;

    /**
     * @var Grinder
     * @ORM\ManyToOne(targetEntity="Grinder", inversedBy="reports")
     * @ORM\JoinColumn(name="grinder_id", referencedColumnName="id")
     */
    protected $grinder;

    /**
     * @ORM\Column(type="integer", nullable=false)
     */
    protected $version;

    /**
     * @ORM\Column(type="integer", nullable=false)
     */
    protected $startMillis;

    /**
     * @ORM\Column(type="integer", nullable=false)
     */
    protected $endMillis;

    /**
     * @ORM\Column(type="integer", nullable=false)
     */
    protected $tareValue;

    /**
     * @ORM\Column(type="integer", nullable=false)
     */
    protected $temporaryTarget;

    /**
     * @ORM\Column(type="integer", nullable=false)
     */
    protected $grindTargetTime;

    /**
     * @ORM\Column(type="integer", nullable=false)
     */
    protected $purgeTargetTime;

    /**
     * @ORM\Column(type="integer", nullable=false)
     */
    protected $grindTargetWeight;

    /**
     * @ORM\Column(type="integer", nullable=false)
     */
    protected $productivity;

    /**
     * @ORM\Column(type="float", nullable=false)
     */
    protected $scaleCalibration;

    /**
     * @ORM\Column(type="integer", nullable=false)
     */
    protected $reactionTime;

    /**
     * @ORM\Column(type="integer", nullable=false)
     */
    protected $type;

    /**
     * @ORM\Column(type="json", nullable=false, options={"jsonb": true})
     */
    protected $measuringData;

    /** @var MeasuringPoint[] */
    protected $measuringPoints;

    /**
     * @param MeasuringPoint[] $measuringPoints
     */
    public function __construct(
        Grinder $grinder,
        int $version,
        int $startMillis,
        int $endMillis,
        int $tareValue,
        int $temporaryTarget,
        int $grindTargetTime,
        int $purgeTargetTime,
        int $grindTargetWeight,
        int $productivity,
        float $scaleCalibration,
        int $reactionTime,
        int $type,
        array $measuringPoints
    ) {
        $this->id = Uuid::v4();
        $this->createdAt = new \DateTimeImmutable();
        $this->grinder = $grinder;
        $this->version = $version;
        $this->startMillis = $startMillis;
        $this->endMillis = $endMillis;
        $this->tareValue = $tareValue;
        $this->temporaryTarget = $temporaryTarget;
        $this->grindTargetTime = $grindTargetTime;
        $this->purgeTargetTime = $purgeTargetTime;
        $this->grindTargetWeight = $grindTargetWeight;
        $this->productivity = $productivity;
        $this->scaleCalibration = $scaleCalibration;
        $this->reactionTime = $reactionTime;
        $this->setMeasuringPoints($measuringPoints);
        $this->type = $type;
    }

    public function getGrinder(): ?Grinder
    {
        return $this->grinder;
    }

    public function getVersion(): int
    {
        return $this->version;
    }

    public function getStartMillis(): int
    {
        return $this->startMillis;
    }

    public function getEndMillis(): int
    {
        return $this->endMillis;
    }

    public function getTareValue(): int
    {
        return $this->tareValue;
    }

    public function getTemporaryTarget(): int
    {
        return $this->temporaryTarget;
    }

    public function getGrindTargetTime(): int
    {
        return $this->grindTargetTime;
    }

    public function getPurgeTargetTime(): int
    {
        return $this->purgeTargetTime;
    }

    public function getGrindTargetWeight(): int
    {
        return $this->grindTargetWeight;
    }

    public function getProductivity(): int
    {
        return $this->productivity;
    }

    public function getScaleCalibration(): float
    {
        return $this->scaleCalibration;
    }

    public function getReactionTime(): int
    {
        return $this->reactionTime;
    }

    public function getType(): int
    {
        return $this->type;
    }

    /**
     * @param MeasuringPoint[] $measuringPoints
     */
    public function setMeasuringPoints(array $measuringPoints)
    {
        $this->measuringPoints = $measuringPoints;
        $this->measuringData = [];
        foreach ($measuringPoints as $mp) {
            $this->measuringData[$mp->getMicroTime()] = $mp->getRawData();
        }
    }

    public function getMeasuringPoints()
    {
        if ($this->measuringPoints === null) {
            $this->measuringPoints = [];
            foreach ($this->measuringData as $time => $raw) {
                $this->measuringPoints[] = new MeasuringPoint($time, $raw);
            }
        }

        return $this->measuringPoints;
    }

    public function getId(): Uuid
    {
        return $this->id;
    }

    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getDuration(): float
    {
        return ($this->endMillis - $this->startMillis) / 1000;
    }

    public function getTypeString(): string
    {
        return self::$typeMap[$this->type];
    }

    public function getGroundWeight(): ?float
    {
        if (count($this->getMeasuringPoints()) == 0) {
            return null;
        }

        return (array_slice($this->getMeasuringPoints(), -1, 1)[0]->getRawData() - $this->tareValue) / $this->scaleCalibration;
    }

    /**
     * @return RelativeMeasuringPoint[]
     */
    public function getRelativePoints(): array
    {
        $mps = $this->getMeasuringPoints();

        return array_map(function(MeasuringPoint $mp) use ($mps) {
            return new RelativeMeasuringPoint($mp, $this->tareValue, $this->scaleCalibration, $mps[0]);
        }, $mps);
    }

    public function getTargetUnit(): string
    {
        return $this->type == 3 ? 'g' : 's';
    }

    public function getTarget(): ?float
    {
        if ($this->temporaryTarget > 0) {
            return $this->temporaryTarget / 1000;
        }

        switch ($this->type) {
            case 1:
                return $this->purgeTargetTime / 1000;
            case 2:
                return $this->grindTargetTime / 1000;
            case 3:
                return $this->grindTargetWeight / 1000;
        }

        return null;
    }
}

src/Controller/ReportController.php
<?php
declare(strict_types=1);

namespace App\Controller;

use App\Entity\GrindReport;
use App\ReportParser;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Log\LoggerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\Uid\Uuid;

class ReportController extends AbstractController
{
    /**
     * @var LoggerInterface
     */
    private $logger;
    /**
     * @var SerializerInterface
     */
    private $serializer;
    /**
     * @var ReportParser
     */
    private $parser;
    /**
     * @var EntityManagerInterface
     */
    private $em;

    public function __construct(ReportParser $parser, EntityManagerInterface $em, SerializerInterface $serializer)
    {
        $this->serializer = $serializer;
        $this->parser = $parser;
        $this->em = $em;
    }

    /**
     * @Route("/grinders/{grinder}/report/{id}", name="report_show")
     * @ParamConverter("report")
     */
    public function show(GrindReport $report)
    {
        return $this->render("report/show.html.twig", [
            'report' => $report
        ]);
    }

    /**
     * @Route("/report", name="take_report")
     */
    public function takeReport(Request $request)
    {
        $report = $this->parser->parseReport(Uuid::v5(Uuid::fromString("e9cc7700-9567-4195-ab1e-c44aff846e16"), $request->getUser()), $request->getContent());

        $this->em->persist($report);
        $this->em->flush();

        return new Response("", Response::HTTP_CREATED);
    }
}

templates/report/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <small><a href="{{ path('grinder_show', {'id': report.grinder.id}) }}">&laquo; Back</a></small>

    <h1>{{ report.typeString }}: {{ report.createdAt|date("Y-m-d H:i") }}</h1>
    <strong>{{ report.grinder.manufacturer }} {{ report.grinder.model }}</strong>

    <h2>Grind parameters</h2>
    <dl>
        <dt>Duration</dt>
        <dd>{{ report.duration|round(2) }} s</dd>
        {% if report.type != 0 %}
        <dt>Target</dt>
        <dd>
            {{ report.target }} {{ report.targetUnit }}
        </dd>
        {% endif %}
    </dl>

    <div style="width:600px; height: 400px">
    <canvas id="myChart" width="600" height="400"></canvas>
    </div>
    <script>
        var ctx = document.getElementById('myChart').getContext('2d');
        var myLineChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: [
                    {% for mp in report.relativePoints %}
                        {{ mp.relativeSeconds|round(2) }},
                    {% endfor %}
                ],
                datasets: [{
                    label: "Weight",
                    data: [
                        {% for mp in report.relativePoints %}
                        {{ mp.weight|round(2) }},
                        {% endfor %}
                    ],
                }]
            }
        });
    </script>

    <h2>Grinder settings</h2>
    <dl>
        <dt>Purge target time</dt>
        <dd>{{ report.purgeTargetTime/1000|round(2) }} s</dd>
        <dt>Grind by time target</dt>
        <dd>{{ report.grindTargetTime/1000|round(2) }} s</dd>
        <dt>Grind by weight target</dt>
        <dd>{{ report.grindTargetWeight/1000|round(2) }} g</dd>
        <dt>Grinder productivity</dt>
        <dd>{{ report.productivity/1000|round(2) }} g/s</dd>
        <dt>Reaction compensation</dt>
        <dd>{{ report.reactionTime/1000|round(2) }} s</dd>
        <dt>Grinder productivity</dt>
        <dd>{{ report.productivity/1000|round(2) }} g/s</dd>
        <dt>Scale ADC calibration value</dt>
        <dd>{{ report.scaleCalibration }}</dd>
    </dl>

    <h2>Weights</h2>
    <table>
        <thead>
        <tr>
            <th>Timestamp</th>
            <th>Weight</th>
        </tr>
        </thead>
        <tbody>
        {% for mp in report.relativePoints %}
            <tr>
                <td>{{ mp.relativeSeconds }}</td>
                <td>{{ mp.weight|round(2) }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}